[package]
name = "start"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctrlc = "3.2.5"
chrono = "0.4.19"
reqwest = { version = "0.11", features = ["blocking", "json"] }
scraper = "0.14.0"